apiVersion: v1
kind: Service
metadata:
  name: sarthi-backend
  namespace: sarthi-prod
  labels:
    app: sarthi-backend
spec:
  selector:
    app: sarthi-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
